import './js/mobile-menu';
import './js/anchor-scroll';
import './js/buy-modal';
import './js/franchise';
import './js/gallery-swiper';
import './js/locations-modal';
import './js/read-more';
import './js/products-modal';
import './js/sroll-up';